spring.application.name=chat-app-backend
spring.data.mongodb.uri=mongodb://localhost:27017/chatapp
// key
hoidanit.jwt.base64-secret=Co4KoA4sjTcKd6hyaPqFAzQC5R5i2LDpHjlWXvEOaVaub3k1PAYNwTLkcalcfiWA8Miu2QKNRyeRLcQ8QVy8dQ==
//time cua accesstoken
hoidanit.jwt.access-token-validity-in-seconds=8640000
hoidanit.jwt.refresh-token-validity-in-seconds=8640000
//file
#default = 1MB  file upload c?n bn mb
spring.servlet.multipart.max-file-size=50MB

#default = 10 MB (form data)  m?i l?n g?i request v?i upload t?n bn ví d? file upload là 1mb thì 10mb là ???c g?i 10 l?n
spring.servlet.multipart.max-request-size=50MB
#base-path
hoidanit.upload-file.base-uri=file:///C:/Hoidanit/upload/